export const text = {
  EN: [
    'Bookjack is a simple reader with magical powers. It takes a lot of willpower to read a lot. Bookjack will give you that power.',
    "Pick a book you've been wanting to read for a long time. Make a bet that you will do it, for example, in 1 week. If you don't make it, you will lose your money. If you succeed, the money will be returned to you. You will not receive profit, but the victory will pay for the time spent.",
    'How Bookjack works. \n Bookjack works on the Near blockchain.It is a simple open source smart contract. A smart contract is a smart wallet that manages its money according to a strictly defined algorithm. It cannot be changed, blocked or hacked.',
    'By placing a bet, you transfer money to this wallet. Now they are stored there until the end of the transaction and no one is able to extract them from it. If you comply with his requirements, he sends your money to your wallet. If not, it sends your bet to the casino wallet.',
    'To fulfill his requirements, you need to open the book and start flipping through the pages. At this point, the timer will start. If you fall asleep and stop flipping pages, the timer will stop. By placing a bid, you specify the number of hours you promise to read and a deadline. Before the end of this period, you must reset the timer.',
    'You can cheat Bookjack by mindlessly flipping pages without reading the content. Bookjack is a truly smart smart contract, but alas, it is not able to defeat the human intellect. To protect you from his own ruse, Bookjack invites you to read books from his library. These books contain simple questions. If you answer even one wrong, you lose.',
    'We wish you lucky reading.',
  ],
  RU: [
    'Bookjack это простая читалка, с волшебной силой. Чтобы много читать необходима большая  сила воли. Bookjack даст вам эту силу.',
    'Выберите книгу, которую давно хотели прочитать. Сделайте ставку, что сделаете это, например за 1 неделю. Если не успеете, вы проиграете свои деньги. Если успеете деньги вернутся вам обратно. Прибыли вы не получите, но победа окупит потраченное время.',
    'Как работает Bookjack. \n Bookjack работает на блоечейне неар. Это простой смарт-контракт с открытым исходным кодом. Смарт-контракт это умный кошелек, который распоряжается  своими деньгами по строго заданному алгоритму. Его невозможно изменить, заблокировать или взломать.',
    'Делая ставку вы переводите деньги на этот кошелек. Теперь они хранятся там до конца сделки и никто не в силах извлечь их из него. Если вы выполняете его требования, он пересылает ваши деньги, на ваш кошелек. Если нет,он отправляет вашу ставку на кошелек казино.',
    'Чтобы выполнить его требования Вам необходимо открыть книгу и начать листать страницы. В этот момент включится таймер. Если вы уснете и перестанете листать страницы, таймер остановится. Делая ставку вы указываете количество часов, которые вы обещаете читать и крайний срок. До конца этого срока вы должны обнулить таймер.',
    'Вы можете обмануть Bookjack, бездумно листая страницы, не вчитываяся в содержимое. Bookjack по-настоящему умный смарт-контракт, но увы, он не в силах победить человеческий интеллект. Чтобы защитить Вас от собственной хитрости, Bookjack предлагает вам читать книги из его библиотеки. В этих книгах содержатся простые вопросы. Если Вы ответите неверно хотябы на один, вы проиграете.',
    'Желаем Вам удачного чтения.',
  ],
  CHN: [
    'Bookjack 是一个简单的阅读器，具有神奇的力量。 大量阅读需要很大的意志力。 Bookjack 会给你这种力量。',
    '选一本你想读很久的书。 打赌你会在 1 周内做到这一点。 如果你不成功，你就会失去你的钱。 如果你成功了，钱会退还给你。 您不会获得利润，但胜利会为所花费的时间付出代价。',
    'Bookjack 的工作原理。 \n Bookjack 在附近的区块链上工作。 它是一个简单的开源智能合约。 智能合约是一种智能钱包，它根据严格定义的算法管理资金。 它不能被更改、阻止或黑客攻击。',
    '通过下注，您将钱转入此钱包。 现在它们一直存储在那里，直到交易结束，没有人能够从中提取它们。 如果你满足他的要求，他就会把你的钱打到你的钱包里。 如果没有，它会将您的赌注发送到赌场钱包。',
    '为了满足他的要求，您需要打开这本书并开始翻页。 此时，计时器将启动。 如果您入睡并停止翻页，计时器将停止。 通过出价，您指定了您承诺阅读的小时数和截止日期。 在此期间结束之前，您必须重置计时器。',
    '你可以在不阅读内容的情况下盲目翻页来愚弄 Bookjack。 Bookjack 是一个真正聪明的智能合约，可惜它无法战胜人类的智慧。 为了保护你免受他自己的诡计，书杰克邀请你阅读他图书馆的书。 这些书包含简单的问题。 如果你连答错一个，你就输了。',
    '祝您阅读愉快。',
  ],
  FR: [
    'Bookjack est un lecteur simple doté de pouvoirs magiques. Il faut beaucoup de volonté pour lire beaucoup. Bookjack vous donnera ce pouvoir.',
    "Choisissez un livre que vous vouliez lire depuis longtemps. Faites le pari que vous le ferez, par exemple, en 1 semaine. Si vous ne le faites pas, vous perdrez votre argent. Si vous réussissez, l'argent vous sera rendu. Vous ne recevrez pas de profit, mais la victoire paiera pour le temps passé.",
    "Comment fonctionne Bookjack. \n Bookjack travaille sur la blockchain à proximité. Il s'agit d'un simple contrat intelligent open source. Un contrat intelligent est un portefeuille intelligent qui gère son argent selon un algorithme strictement défini. Il ne peut pas être modifié, bloqué ou piraté.",
    "En plaçant un pari, vous transférez de l'argent sur ce portefeuille. Désormais, ils y sont stockés jusqu'à la fin de la transaction et personne ne peut les en extraire. Si vous vous conformez à ses exigences, il envoie votre argent dans votre portefeuille. Sinon, il envoie votre pari au portefeuille du casino.",
    "Pour répondre à ses exigences, vous devez ouvrir le livre et commencer à feuilleter les pages. À ce stade, le chronomètre démarre. Si vous vous endormez et arrêtez de tourner les pages, le chronomètre s'arrêtera. En enchérissant, vous précisez le nombre d'heures que vous vous engagez à lire et un délai. Avant la fin de cette période, vous devez réinitialiser la minuterie.",
    "Vous pouvez tromper Bookjack en tournant sans réfléchir les pages sans lire le contenu. Bookjack est un contrat intelligent vraiment intelligent, mais hélas, il n'est pas capable de vaincre l'intellect humain. Pour vous protéger de sa propre ruse, bookjack vous invite à lire les livres de sa bibliothèque. Ces livres contiennent des questions simples. Si vous répondez ne serait-ce qu'une seule fois, vous perdez.",
    'Nous vous souhaitons une bonne lecture.',
  ],
  GRM: [
    'Bookjack ist ein einfaches Lesebuch mit magischen Kräften. Es braucht viel Willenskraft, um viel zu lesen. Bookjack wird dir diese Kraft geben.',
    'Suchen Sie sich ein Buch aus, das Sie schon lange lesen wollten. Wetten Sie, dass Sie es zum Beispiel in 1 Woche schaffen. Wenn Sie es nicht schaffen, verlieren Sie Ihr Geld. Wenn Sie erfolgreich sind, wird Ihnen das Geld zurückerstattet. Sie erhalten keinen Gewinn, aber der Sieg wird für die aufgewendete Zeit bezahlt.',
    'So funktioniert Bookjack. \n Bookjack arbeitet an der Blockchain in der Nähe. Es ist ein einfacher Open Source Smart Contract. Ein Smart Contract ist eine Smart Wallet, die ihr Geld nach einem fest definierten Algorithmus verwaltet. Es kann nicht geändert, blockiert oder gehackt werden.',
    'Indem Sie eine Wette platzieren, überweisen Sie Geld auf diese Geldbörse. Jetzt werden sie dort bis zum Ende der Transaktion gespeichert und niemand kann sie daraus extrahieren. Wenn Sie seine Anforderungen erfüllen, sendet er Ihr Geld an Ihre Brieftasche. Wenn nicht, wird Ihre Wette an die Casino-Brieftasche gesendet.',
    'Um seine Anforderungen zu erfüllen, müssen Sie das Buch öffnen und anfangen, durch die Seiten zu blättern. An diesem Punkt wird der Timer gestartet. Wenn Sie einschlafen und aufhören, Seiten umzublättern, stoppt der Timer. Indem Sie ein Gebot abgeben, geben Sie die Anzahl der Stunden, die Sie zu lesen versprechen, und eine Frist an. Vor Ablauf dieses Zeitraums müssen Sie den Timer zurücksetzen.',
    'Sie können Bookjack täuschen, indem Sie gedankenlos Seiten umblättern, ohne den Inhalt zu lesen. Bookjack ist ein wirklich intelligenter Smart Contract, aber leider ist er nicht in der Lage, den menschlichen Intellekt zu besiegen. Um Sie vor seiner eigenen List zu schützen, lädt Bookjack Sie ein, Bücher aus seiner Bibliothek zu lesen. Diese Bücher enthalten einfache Fragen. Wenn Sie auch nur eine falsch beantworten, verlieren Sie.',
    'Wir wünschen Ihnen viel Spaß beim Lesen.',
  ],
  ITL: [
    'Bookjack è un semplice lettore con poteri magici. Ci vuole molta forza di volontà per leggere molto. Bookjack ti darà quel potere.',
    'Scegli un libro che desideri leggere da molto tempo. Scommetti che lo farai, ad esempio, in 1 settimana. Se non ce la fai, perderai i tuoi soldi. Se ci riesci, i soldi ti verranno restituiti. Non riceverai profitti, ma la vittoria pagherà per il tempo speso.',
    'Come funziona Book Jack. \n Bookjack lavora sulla blockchain vicino. È un semplice contratto intelligente open source. Uno smart contract è un portafoglio intelligente che gestisce i suoi soldi secondo un algoritmo rigorosamente definito. Non può essere modificato, bloccato o violato.',
    'Effettuando una scommessa, trasferisci denaro a questo portafoglio. Ora sono archiviati lì fino alla fine della transazione e nessuno è in grado di estrarli da essa. Se rispetti i suoi requisiti, invia i tuoi soldi al tuo portafoglio. In caso contrario, invia la tua scommessa al portafoglio del casinò.',
    "Per soddisfare le sue esigenze, devi aprire il libro e iniziare a sfogliare le pagine. A questo punto partirà il timer. Se ti addormenti e smetti di sfogliare le pagine, il timer si fermerà. Facendo un'offerta, specifichi il numero di ore che prometti di leggere e una scadenza. Prima della fine di questo periodo, è necessario reimpostare il timer.",
    "Puoi ingannare Bookjack sfogliando le pagine senza pensare senza leggere il contenuto. Bookjack è un contratto intelligente davvero intelligente, ma purtroppo non è in grado di sconfiggere l'intelletto umano. Per proteggerti dal suo stesso stratagemma, Bookjack ti invita a leggere i libri della sua biblioteca. Questi libri contengono domande semplici. Se rispondi anche a una sola risposta sbagliata, perdi.",
    'Vi auguriamo buona lettura.',
  ],
  SPN: [
    'Bookjack es un simple lector con poderes mágicos. Se necesita mucha fuerza de voluntad para leer mucho. Bookjack te dará ese poder.',
    'Elige un libro que hayas querido leer durante mucho tiempo. Haz una apuesta a que lo harás, por ejemplo, en 1 semana. Si no lo hace, perderá su dinero. Si tiene éxito, se le devolverá el dinero. No recibirá ganancias, pero la victoria pagará por el tiempo invertido.',
    'Cómo funciona Bookjack. \n Bookjack trabaja en la cadena de bloques cercana. Es un simple contrato inteligente de código abierto. Un contrato inteligente es una billetera inteligente que administra su dinero de acuerdo con un algoritmo estrictamente definido. No se puede cambiar, bloquear o hackear.',
    'Al hacer una apuesta, transfieres dinero a esta billetera. Ahora se almacenan allí hasta el final de la transacción y nadie puede extraerlos de ella. Si cumple con sus requisitos, le envía su dinero a su billetera. Si no, envía su apuesta a la billetera del casino.',
    'Para cumplir con sus requisitos, debe abrir el libro y comenzar a hojear las páginas. En este punto, el temporizador se iniciará. Si te quedas dormido y dejas de pasar las páginas, el temporizador se detendrá. Al hacer una oferta, especifica la cantidad de horas que promete leer y una fecha límite. Antes de que finalice este período, debe restablecer el temporizador.',
    'Puedes engañar a Bookjack pasando páginas sin pensar sin leer el contenido. Bookjack es un contrato inteligente verdaderamente inteligente, pero, por desgracia, no puede vencer al intelecto humano. Para protegerte de su propia artimaña, bookjack te invita a leer libros de su biblioteca. Estos libros contienen preguntas simples. Si respondes aunque sea una sola incorrectamente, pierdes.',
    'Le deseamos una feliz lectura.',
  ],
  日本語: [
    'ブックジャックは、魔法の力を持つシンプルなリーダーです。 たくさん読むにはかなりの意志が必要です。 ブックジャックはその力を与えてくれます。',
    'ずっと読みたかった本を選んでください。 たとえば、1週間でそれを行うことに賭けてください。 うまくいかなければ、お金を失うことになります。 成功すればお金は戻ってきます。 利益は得られませんが、勝利は費やされた時間に対して支払われます。',
    'ブックジャックの仕組み。 \n ブックジャックは近くのブロックチェーンで動作します。 シンプルなオープンソースのスマート コントラクトです。 スマート コントラクトは、厳密に定義されたアルゴリズムに従ってお金を管理するスマート ウォレットです。 変更、ブロック、ハッキングすることはできません。',
    '賭けをすると、このウォレットに送金されます。 現在、それらはトランザクションが終了するまでそこに保管され、誰もそこからそれらを抽出することはできません. 彼の要求に従えば、彼はあなたのお金をあなたの財布に送金します。 そうでない場合は、ベットがカジノ ウォレットに送信されます。',
    '彼の要件を満たすには、本を開いてページをめくる必要があります。 この時点で、タイマーが開始されます。 眠りに落ちてページをめくるのをやめると、タイマーが止まります。 入札を行うことにより、読むことを約束する時間数と締め切りを指定します。 この期間が終了する前に、タイマーをリセットする必要があります。',
    '内容を読まずに無意識にページをめくると、Bookjack をだますことができます。 Bookjack は真にスマートなスマート コントラクトですが、残念ながら、人間の知性を打ち負かすことはできません。 ブックジャックは自分の策略からあなたを守るために、彼のライブラリーから本を読むようにあなたを招待します。 これらの本には簡単な質問が含まれています。 1問でも間違えると負け。',
    '楽しくお読みいただければ幸いです。',
  ],
  韓國語: [
    'Bookjack은 마법의 힘을 가진 단순한 리더입니다. 많이 읽으려면 많은 의지력이 필요합니다. 북잭이 그 힘을 드립니다.',
    '오랫동안 읽고 싶었던 책을 선택하십시오. 예를 들어, 1주일 안에 할 것이라고 내기를 하십시오. 성공하지 못하면 돈을 잃게 됩니다. 성공하면 돈이 반환됩니다. 당신은 이익을 얻지 못하지만 승리는 보낸 시간에 대한 대가를 치를 것입니다.',
    '북잭 작동 방식. \n Bookjack은 가까운 블록체인에서 작동합니다. 간단한 오픈 소스 스마트 계약입니다. 스마트 계약은 엄격하게 정의된 알고리즘에 따라 돈을 관리하는 스마트 지갑입니다. 변경, 차단 또는 해킹할 수 없습니다.',
    '내기를 걸면 이 지갑으로 돈을 이체하게 됩니다. 이제 그들은 거래가 끝날 때까지 거기에 저장되며 아무도 그것을 추출할 수 없습니다. 당신이 그의 요구 사항을 준수하면 그는 당신의 돈을 당신의 지갑으로 보냅니다. 그렇지 않은 경우 내기를 카지노 지갑으로 보냅니다.',
    '그의 요구 사항을 충족하려면 책을 열고 페이지를 넘기기 시작해야 합니다. 이 시점에서 타이머가 시작됩니다. 잠들고 페이지 넘기기를 중지하면 타이머가 중지됩니다. 입찰을 하면 독서를 약속하는 시간과 기한을 지정하게 됩니다. 이 기간이 끝나기 전에 타이머를 재설정해야 합니다.',
    '내용을 읽지 않고 아무 생각 없이 페이지를 넘기면 Bookjack을 속일 수 있습니다. 북잭은 진정으로 스마트한 스마트 계약이지만, 아쉽게도 인간의 지능을 이길 수는 없습니다. 자신의 책략으로부터 당신을 보호하기 위해 북잭은 그의 서재에서 책을 읽도록 당신을 초대합니다. 이 책에는 간단한 질문이 포함되어 있습니다. 하나라도 틀리면 지는 겁니다.',
    '우리는 당신이 행복한 독서를 기원합니다.',
  ],
  العربية: [
    'Bookjack هو قارئ بسيط يتمتع بقوى سحرية. يتطلب الأمر الكثير من قوة الإرادة لقراءة الكثير. ستمنحك Bookjack هذه القوة.',
    'اختر كتابًا كنت ترغب في قراءته لفترة طويلة. ضع رهانًا على أنك ستفعل ذلك ، على سبيل المثال ، في غضون أسبوع واحد. إذا لم تنجح ، فسوف تخسر أموالك. إذا نجحت ، ستتم إعادة الأموال إليك. لن تحصل على ربح ، لكن النصر سيدفع مقابل الوقت الذي تقضيه.',
    'كيف يعمل Bookjack. \n  يعمل Bookjack على blockchain القريب. إنه عقد ذكي بسيط مفتوح المصدر. العقد الذكي هو محفظة ذكية تدير أموالها وفقًا لخوارزمية محددة بدقة. لا يمكن تغييره أو حظره أو اختراقه.',
    'من خلال وضع الرهان ، تقوم بتحويل الأموال إلى هذه المحفظة. الآن يتم تخزينها هناك حتى نهاية المعاملة ولا يستطيع أحد استخراجها منها. إذا امتثلت لمتطلباته ، فإنه يرسل أموالك إلى محفظتك. إذا لم يكن كذلك ، فإنه يرسل رهانك إلى محفظة الكازينو.',
    'لتحقيق متطلباته ، تحتاج إلى فتح الكتاب والبدء في التقليب بين الصفحات. في هذه المرحلة ، سيبدأ المؤقت. إذا نمت وتوقفت عن تقليب الصفحات ، فسيتوقف المؤقت. من خلال تقديم العطاء ، فإنك تحدد عدد الساعات التي تتعهد بقراءتها والموعد النهائي. قبل نهاية هذه الفترة ، يجب إعادة ضبط المؤقت.',
    'يمكنك خداع Bookjack عن طريق تقليب الصفحات بلا تفكير دون قراءة المحتوى. Bookjack هو عقد ذكي حقًا ، لكنه للأسف غير قادر على هزيمة الفكر البشري. لحمايتك من حيلته ، يدعوك Bookjack لقراءة الكتب من مكتبته. تحتوي هذه الكتب على أسئلة بسيطة. إذا أجبت حتى خطأ واحد ، فإنك تخسر.',
    'نتمنى لك قراءة سعيدة.',
  ],
  עִבְרִית: [
    'Bookjack הוא קורא פשוט עם כוחות קסם. צריך הרבה כוח רצון לקרוא הרבה. Bookjack ייתן לך את הכוח הזה.',
    'בחר ספר שרצית לקרוא כבר הרבה זמן. הימור שתעשה זאת, למשל, תוך שבוע. אם לא תצליח, תפסיד את כספך. אם תצליח, הכסף יוחזר לך. לא תקבל רווח, אבל הניצחון ישלם עבור הזמן שהושקע.',
    "איך Bookjack עובד. \n Bookjack עובד על הבלוקצ'יין ליד. זהו חוזה חכם פשוט בקוד פתוח. חוזה חכם הוא ארנק חכם שמנהל את כספו לפי אלגוריתם מוגדר בהחלט. לא ניתן לשנות, לחסום או לפרוץ אותו.",
    'על ידי ביצוע הימור, אתה מעביר כסף לארנק הזה. כעת הם מאוחסנים שם עד לסיום העסקה ואף אחד לא מסוגל לחלץ אותם ממנה. אם אתה עומד בדרישות שלו, הוא שולח את הכסף שלך לארנק שלך. אם לא, זה שולח את ההימור שלך לארנק הקזינו.',
    'כדי למלא את דרישותיו, עליך לפתוח את הספר ולהתחיל לדפדף בין הדפים. בשלב זה, הטיימר יתחיל. אם אתה נרדם ותפסיק לדפדף, הטיימר יפסיק. בהגשת הצעה, אתה מציין את מספר השעות שאתה מבטיח לקרוא ומועד אחרון. לפני תום תקופה זו, עליך לאפס את הטיימר.',
    "אתה יכול לשטות בבוקג'ק על ידי דפדוף חסר דעת מבלי לקרוא את התוכן. Bookjack הוא חוזה חכם באמת, אבל אבוי, הוא לא מסוגל להביס את האינטלקט האנושי. כדי להגן עליך מהתחבולה שלו, Bookjack מזמין אותך לקרוא ספרים מהספרייה שלו. ספרים אלה מכילים שאלות פשוטות. אם אתה עונה אפילו לא נכון אחד, אתה מפסיד.",
    'אנו מאחלים לך קריאה מהנה.',
  ],
};
